import { User } from '../App';

export const mockUsers: User[] = [
  { id: 2, name: 'Priya Sharma', role: 'admin', password: 'admin123', permissions: ['all'] },
];

// mockAnimals is no longer needed as data will be fetched from the backend.
// We can remove this array completely.
export const mockAnimals: any[] = [];

export const translations = {
  en: {
    zookeeper: 'Zookeeper',
    admin: 'Admin',
    vet: 'Vet Doctor',
    officer: 'Forest Officer',
    dashboard: 'Dashboard',
    myAnimals: 'My Animals',
    addLog: 'Add Log',
    viewProfile: 'View Profile',
    todaysTasks: "Today's Tasks",
    pendingLogs: 'Pending Logs',
    dailyLog: 'Daily Log',
    observationPlaceholder: 'Enter daily observations here... (e.g., animal behavior, feeding, health notes)',
    submitObservation: 'Submit Text Observation',
    processing: 'Processing...',
    errorOccurred: 'An Error Occurred',
    processedData: 'Processed Data',
    date: 'Date',
    healthSummary: 'Health Summary',
    waterProvided: 'Clean Water Provided',
    enclosureClean: 'Enclosure Cleaned',
    normalBehavior: 'Normal Behavior',
    abnormalBehaviorDetails: 'Abnormal Behavior Details',
    enterObservation: 'Please enter an observation.',
    observationProcessedSuccess: 'Observation processed and saved!',
    processingError: 'Failed to process observation.',
    recorderStatus: 'Recorder Status',
    startRecording: 'Start Recording',
    stopRecording: 'Stop Recording',
    voiceLog: 'Voice Log',
    textLog: 'Text Log',
    healthAssessment: 'Health Assessment',
    mood: 'Mood',
    appetite: 'Appetite',
    movement: 'Movement',
    agitated: 'Agitated',
    calm: 'Calm',
    low: 'Low',
    high: 'High',
    slow: 'Slow',
    active: 'Active',
    injuriesReport: 'Injuries / Report',
    enterInjuries: 'Enter any injuries or specific observations...',
    submitVoiceLog: 'Submit Voice Log',
    excellent: 'Excellent',
    good: 'Good',
    fair: 'Fair',
    poor: 'Poor',
    alerts: 'Alerts',
    settings: 'Settings',
    notifications: 'Notifications',
    logout: 'Logout',
    cancel: 'Cancel',
    sendAlert: 'Send Alert',
    sosAlert: 'SOS Alert',
    manageUsers: 'Manage Users',
    addAnimal: 'Add Animal',
    mediaUploads: 'Media Uploads',
    uploadImage: 'Upload Image',
    uploadVideo: 'Upload Video',
    transcribingAudio: 'Transcribing audio, please wait...',
    transcriptionSuccess: 'Audio transcribed successfully!',
    transcriptionError: 'Failed to transcribe audio.',
    shareWith: 'Share With',
    selectUsersToShare: 'Select individual users to share this log with',
    notifyVetDepartment: 'Notify Vet Department of this log',
    healthReports: 'Health Reports',
    voiceLogs: 'Voice Logs',

    // Observation Questions
    q1: 'How did the animal eat and drink today, and how was its digestion?',
    q2: 'Did you notice any injury, illness, weakness, or abnormal physical condition?',
    q3: 'How was the animal\'s behaviour/activity compared to normal?',
    q4: 'Was there any mating, heat, pregnancy, or birth observed?',
    q5: 'Was there any death or critical condition?',
    q6: 'Enclosure condition & cleanliness?',
    q7: 'Hygiene/Pest/Safety issues?',
    q8: 'Staff attendance/uniform/health?',
    q9: 'Any other unusual/important records?',

    // Form Labels
    animalHealthForm: 'Animal Health Form',
    kraalHealthForm: 'Kraal Health Form',
    feedTaken: 'Have all animals taken their feed on time?',
    feedConsumption: 'Approximate feed consumption',
    speciesNotFed: 'Species/Animal name not fed',
    stoolCondition: 'Stool condition',
    eveningFeedTaken: 'Have all animals consumed evening feed and water?',
    isInjured: 'Is any animal injured?',
    injuryType: 'Injury type',
    injuryDetails: 'Injury details',
    birthObserved: 'Has any animal given birth?',
    birthDetails: 'Birth details',
    motherName: 'Mother name',
    fatherName: 'Father name',
    motherCaring: 'Is mother caring for the newborn?',
    feedingFrequency: 'Feeding frequency of newborn',
    deathObserved: 'Has any animal died today?',
    deathDetails: 'Death details',
    sex: 'Sex',
    age: 'Age',
    femaleInHeat: 'Is any female animal in heat?',
    matingOccurred: 'Has mating occurred?',
    abnormalBehavior: 'Is any abnormal behaviour observed?',
    abnormalBehaviorDetails: 'Abnormal behaviour details',

    // Kraal Health
    cleanlinessChecked: 'Enclosure cleanliness checked',
    waterTroughCleaned: 'Water trough cleaned',
    fenceCondition: 'Fence condition satisfactory',
    moatCondition: 'Moat condition',
    pestControlTaken: 'Fly and mosquito control measures taken',
    staffStatus: 'Staff uniform and health satisfactory',
    weeklyCleaningType: 'Weekly cleaning done with',

    // Options
    hard: 'Hard',
    soft: 'Soft',
    worms: 'Worms',
    blood: 'Blood',
    normal: 'Normal',
    minor: 'Minor',
    severe: 'Severe',
    head: 'Head',
    once: 'Once',
    twice: 'Twice',
    thrice: 'Thrice',
    fourOrMore: 'Four or more times',
    male: 'Male',
    female: 'Female',
    infant: 'Infant',
    young: 'Young',
    adult: 'Adult',
    dry: 'Dry',
    wet: 'Wet',
    sodiumHypochlorite: 'Sodium Hypochlorite',
    limeWater: 'Lime Water',
    none: 'None',

    // Hospital Records
    hospitalRecords: 'Hospital Records',
    observation: 'Observation',
    tests: 'Tests Conducted',
    dosage: 'Dosage Given',
    remarks: 'Remarks',
    addRecord: 'Add Record',

    // Messaging
    messages: 'Messages',
    inbox: 'Inbox',
    sendMessage: 'Send Message',
    selectRecipients: 'Select Recipients',
    allZookeepers: 'All Zookeepers',
    messageSubject: 'Subject',
    messageBody: 'Message',

    // Scheduling
    morningLog: 'Morning Log',
    eveningLog: 'Evening Log',
    deadline: 'Deadline',
    submitted: 'Submitted',
    pending: 'Pending',
    overdue: 'Overdue',
  },
  hi: {
    zookeeper: 'चिड़ियाघर कीपर',
    admin: 'एडमिन',
    vet: 'पशु चिकित्सक',
    officer: 'वन अधिकारी',
    dashboard: 'डैशबोर्ड',
    myAnimals: 'मेरे जानवर',
    addLog: 'लॉग जोड़ें',
    viewProfile: 'प्रोफ़ाइल देखें',
    todaysTasks: 'आज के कार्य',
    pendingLogs: 'लंबित लॉग',
    dailyLog: 'दैनिक लॉग',
    observationPlaceholder: 'दैनिक अवलोकन यहाँ दर्ज करें... (जैसे, जानवर का व्यवहार, भोजन, स्वास्थ्य नोट्स)',
    submitObservation: 'टेक्स्ट अवलोकन सबमिट करें',
    processing: 'प्रोसेस हो रहा है...',
    errorOccurred: 'एक त्रुटि हुई',
    processedData: 'संसाधित डेटा',
    date: 'दिनांक',
    healthSummary: 'स्वास्थ्य सारांश',
    waterProvided: 'साफ पानी उपलब्ध',
    enclosureClean: 'बाड़ा साफ',
    normalBehavior: 'सामान्य व्यवहार',
    abnormalBehaviorDetails: 'असामान्य व्यवहार का विवरण',
    enterObservation: 'कृपया एक अवलोकन दर्ज करें।',
    observationProcessedSuccess: 'अवलोकन संसाधित और सहेजा गया!',
    processingError: 'अवलोकन संसाधित करने में विफल।',
    recorderStatus: 'रिकॉर्डर स्थिति',
    startRecording: 'रिकॉर्डिंग शुरू करें',
    stopRecording: 'रिकॉर्डिंग बंद करें',
    voiceLog: 'वॉयस लॉग',
    textLog: 'टेक्स्ट लॉग',
    healthAssessment: 'स्वास्थ्य मूल्यांकन',
    mood: 'मूड',
    appetite: 'भूख',
    movement: 'गति',
    agitated: 'उत्तेजित',
    calm: 'शांत',
    low: 'कम',
    high: 'उच्च',
    slow: 'धीमा',
    active: 'सक्रिय',
    injuriesReport: 'चोट / रिपोर्ट करें',
    enterInjuries: 'कोई चोट या विशिष्ट अवलोकन दर्ज करें...',
    submitVoiceLog: 'वॉयस लॉग सबमिट करें',
    excellent: 'उत्कृष्ट',
    good: 'अच्छा',
    fair: 'ठीक',
    poor: 'खराब',
    alerts: 'अलर्ट',
    settings: 'सेटिंग्स',
    notifications: 'सूचनाएं',
    logout: 'लॉगआउट',
    cancel: 'रद्द करें',
    sendAlert: 'अलर्ट भेजें',
    sosAlert: 'SOS अलर्ट',
    manageUsers: 'उपयोगकर्ता प्रबंधित करें',
    addAnimal: 'जानवर जोड़ें',
    mediaUploads: 'मीडिया अपलोड',
    uploadImage: 'छवि अपलोड करें',
    uploadVideo: 'वीडियो अपलोड करें',
    transcribingAudio: 'ऑडियो ट्रांसक्राइब हो रहा है, कृपया प्रतीक्षा करें...',
    transcriptionSuccess: 'ऑडियो सफलतापूर्वक ट्रांसक्राइब हो गया!',
    transcriptionError: 'ऑडियो ट्रांसक्राइब करने में विफल।',
    shareWith: 'साझा करें',
    selectUsersToShare: 'इस लॉग को साझा करने के लिए व्यक्तिगत उपयोगकर्ताओं का चयन करें',
    notifyVetDepartment: 'इस लॉग की पशु चिकित्सा विभाग को सूचित करें',
    healthReports: 'स्वास्थ्य रिपोर्ट',
    voiceLogs: 'वॉयस लॉग',

    // Observation Questions
    q1: 'आज जानवर ने खाना और पानी कैसे लिया, और उसका पाचन कैसा रहा?',
    q2: 'क्या आज जानवर में कोई चोट, बीमारी, कमजोरी या असामान्य शारीरिक स्थिति दिखाई दी?',
    q3: 'आज जानवर का व्यवहार और गतिविधि सामान्य थी या कुछ अलग दिखाई दी?',
    q4: 'क्या आज किसी प्रकार की मेटिंग, हीट की स्थिति, गर्भावस्था या बच्चे का जन्म देखा गया?',
    q5: 'क्या आज बाड़े में किसी जानवर की मृत्यु या गंभीर स्थिति देखी गई?',
    q6: 'आज बाड़े और आसपास की साफ़-सफाई और रखरखाव की स्थिति कैसी रही?',
    q7: 'क्या आज स्वच्छता, मच्छर, मक्खी या सुरक्षा से जुड़ी कोई समस्या देखी गई?',
    q8: 'क्या आज कर्मचारियों की उपस्थिति, वर्दी और स्वास्थ्य की स्थिति सामान्य रही?',
    q9: 'क्या आज कोई अन्य विशेष या महत्वपूर्ण बात है जिसे दर्ज किया जाना चाहिए?',

    // Form Labels
    animalHealthForm: 'पशु स्वास्थ्य फॉर्म',
    kraalHealthForm: 'बाड़ा स्वास्थ्य फॉर्म',
    feedTaken: 'क्या सभी जानवरों ने समय पर अपना चारा लिया?',
    feedConsumption: 'अनुमानित चारा खपत',
    speciesNotFed: 'प्रजाति/जानवर का नाम जिसने नहीं खाया',
    stoolCondition: 'मल की स्थिति',
    eveningFeedTaken: 'क्या सभी जानवरों ने शाम का चारा और पानी लिया?',
    isInjured: 'क्या कोई जानवर घायल है?',
    injuryType: 'चोट का प्रकार',
    injuryDetails: 'चोट का विवरण',
    birthObserved: 'क्या किसी जानवर ने बच्चे को जन्म दिया?',
    birthDetails: 'जन्म का विवरण',
    motherName: 'माँ का नाम',
    fatherName: 'पिता का नाम',
    motherCaring: 'क्या माँ नवजात की देखभाल कर रही है?',
    feedingFrequency: 'नवजात को दूध पिलाने की आवृत्ति',
    deathObserved: 'क्या आज किसी जानवर की मृत्यु हुई?',
    deathDetails: 'मृत्यु का विवरण',
    sex: 'लिंग',
    age: 'आयु',
    femaleInHeat: 'क्या कोई मादा जानवर हीट में है?',
    matingOccurred: 'क्या मेटिंग हुई?',
    abnormalBehavior: 'क्या कोई असामान्य व्यवहार देखा गया?',
    abnormalBehaviorDetails: 'असामान्य व्यवहार का विवरण',

    // Kraal Health
    cleanlinessChecked: 'बाड़े की सफाई जांची गई',
    waterTroughCleaned: 'पानी का गर्त साफ किया गया',
    fenceCondition: 'बाड़ की स्थिति संतोषजनक',
    moatCondition: 'खाई की स्थिति',
    pestControlTaken: 'मक्खी और मच्छर नियंत्रण उपाय किए गए',
    staffStatus: 'कर्मचारी वर्दी और स्वास्थ्य संतोषजनक',
    weeklyCleaningType: 'साप्ताहिक सफाई किसके साथ की गई',

    // Options
    hard: 'कठोर',
    soft: 'मुलायम',
    worms: 'कीड़े',
    blood: 'रक्त',
    normal: 'सामान्य',
    minor: 'मामूली',
    severe: 'गंभीर',
    head: 'सिर',
    once: 'एक बार',
    twice: 'दो बार',
    thrice: 'तीन बार',
    fourOrMore: 'चार या अधिक बार',
    male: 'नर',
    female: 'मादा',
    infant: 'शिशु',
    young: 'युवा',
    adult: 'वयस्क',
    dry: 'सूखा',
    wet: 'गीला',
    sodiumHypochlorite: 'सोडियम हाइपोक्लोराइट',
    limeWater: 'चूने का पानी',
    none: 'कोई नहीं',

    // Hospital Records
    hospitalRecords: 'अस्पताल रिकॉर्ड',
    observation: 'अवलोकन',
    tests: 'किए गए परीक्षण',
    dosage: 'दी गई खुराक',
    remarks: 'टिप्पणियाँ',
    addRecord: 'रिकॉर्ड जोड़ें',

    // Messaging
    messages: 'संदेश',
    inbox: 'इनबॉक्स',
    sendMessage: 'संदेश भेजें',
    selectRecipients: 'प्राप्तकर्ता चुनें',
    allZookeepers: 'सभी चिड़ियाघर रक्षक',
    messageSubject: 'विषय',
    messageBody: 'संदेश',

    // Scheduling
    morningLog: 'सुबह का लॉग',
    eveningLog: 'शाम का लॉग',
    deadline: 'समय सीमा',
    submitted: 'सबमिट किया गया',
    pending: 'लंबित',
    overdue: 'समय सीमा समाप्त',
  },
};
