import { User } from '../App';

export const mockUsers: User[] = [
  { id: 2, name: 'Priya Sharma', role: 'admin', password: 'admin123', permissions: ['all'] },
];

// mockAnimals is no longer needed as data will be fetched from the backend.
// We can remove this array completely.
export const mockAnimals: any[] = [];

export const translations = {
  en: {
    zookeeper: 'Zookeeper',
    admin: 'Admin',
    vet: 'Vet Doctor',
    officer: 'Forest Officer',
    dashboard: 'Dashboard',
    myAnimals: 'My Animals',
    addLog: 'Add Log',
    viewProfile: 'View Profile',
    todaysTasks: "Today's Tasks",
    pendingLogs: 'Pending Logs',
    dailyLog: 'Daily Log',
    observationPlaceholder: 'Enter daily observations here... (e.g., animal behavior, feeding, health notes)',
    submitObservation: 'Submit Text Observation',
    processing: 'Processing...',
    errorOccurred: 'An Error Occurred',
    processedData: 'Processed Data',
    date: 'Date',
    healthSummary: 'Health Summary',
    waterProvided: 'Clean Water Provided',
    enclosureClean: 'Enclosure Cleaned',
    normalBehavior: 'Normal Behavior',
    abnormalBehaviorDetails: 'Abnormal Behavior Details',
    enterObservation: 'Please enter an observation.',
    observationProcessedSuccess: 'Observation processed and saved!',
    processingError: 'Failed to process observation.',
    recorderStatus: 'Recorder Status',
    startRecording: 'Start Recording',
    stopRecording: 'Stop Recording',
    voiceLog: 'Voice Log',
    textLog: 'Text Log',
    healthAssessment: 'Health Assessment',
    mood: 'Mood',
    appetite: 'Appetite',
    movement: 'Movement',
    agitated: 'Agitated',
    calm: 'Calm',
    low: 'Low',
    high: 'High',
    slow: 'Slow',
    active: 'Active',
    injuriesReport: 'Injuries / Report',
    enterInjuries: 'Enter any injuries or specific observations...',
    submitVoiceLog: 'Submit Voice Log',
    excellent: 'Excellent',
    good: 'Good',
    fair: 'Fair',
    poor: 'Poor',
    alerts: 'Alerts',
    settings: 'Settings',
    notifications: 'Notifications',
    logout: 'Logout',
    cancel: 'Cancel',
    sendAlert: 'Send Alert',
    sosAlert: 'SOS Alert',
    manageUsers: 'Manage Users',
    addAnimal: 'Add Animal',
    mediaUploads: 'Media Uploads',
    uploadImage: 'Upload Image',
    uploadVideo: 'Upload Video',
    transcribingAudio: 'Transcribing audio, please wait...',
    transcriptionSuccess: 'Audio transcribed successfully!',
    transcriptionError: 'Failed to transcribe audio.',
    shareWith: 'Share With',
    selectUsersToShare: 'Select individual users to share this log with',
    notifyVetDepartment: 'Notify Vet Department of this log',
    healthReports: 'Health Reports',
    voiceLogs: 'Voice Logs',

    // Voice Recording Questions - Animal Health
    question1: 'How did the animal eat and drink today, and how was its digestion?',
    question2: 'Did you notice any injury, illness, weakness, or abnormal physical condition in the animal?',
    question3: 'How was the animal\'s behaviour and activity compared to normal?',
    question4: 'Was there any mating activity, heat signs, pregnancy, or birth observed today?',
    question5: 'Was there any death or critical condition observed in the enclosure today?',
    question6: 'How was the condition and cleanliness of the enclosure and surrounding area today?',
    question7: 'Were there any hygiene, pest, or safety issues noticed today?',
    question8: 'Was staff attendance, uniform compliance, and health normal today?',
    question9: 'Is there anything else unusual or important that should be recorded today?',

    // Voice Recording Questions - Enclosure Health
    question10: 'Was enclosure cleanliness checked?',
    question11: 'Was the water trough cleaned?',
    question12: 'Is the fence condition satisfactory?',
    question13: 'What is the moat condition - Dry or Wet?',
    question14: 'Were fly and mosquito control measures taken?',
    question15: 'Is staff uniform and health satisfactory?',
    question16: 'Was weekly cleaning done with Sodium hypochlorite or Lime water?',
  },
  hi: {
    zookeeper: 'चिड़ियाघर कीपर',
    admin: 'एडमिन',
    vet: 'पशु चिकित्सक',
    officer: 'वन अधिकारी',
    dashboard: 'डैशबोर्ड',
    myAnimals: 'मेरे जानवर',
    addLog: 'लॉग जोड़ें',
    viewProfile: 'प्रोफ़ाइल देखें',
    todaysTasks: 'आज के कार्य',
    pendingLogs: 'लंबित लॉग',
    dailyLog: 'दैनिक लॉग',
    observationPlaceholder: 'दैनिक अवलोकन यहाँ दर्ज करें... (जैसे, जानवर का व्यवहार, भोजन, स्वास्थ्य नोट्स)',
    submitObservation: 'टेक्स्ट अवलोकन सबमिट करें',
    processing: 'प्रोसेस हो रहा है...',
    errorOccurred: 'एक त्रुटि हुई',
    processedData: 'संसाधित डेटा',
    date: 'दिनांक',
    healthSummary: 'स्वास्थ्य सारांश',
    waterProvided: 'साफ पानी उपलब्ध',
    enclosureClean: 'बाड़ा साफ',
    normalBehavior: 'सामान्य व्यवहार',
    abnormalBehaviorDetails: 'असामान्य व्यवहार का विवरण',
    enterObservation: 'कृपया एक अवलोकन दर्ज करें।',
    observationProcessedSuccess: 'अवलोकन संसाधित और सहेजा गया!',
    processingError: 'अवलोकन संसाधित करने में विफल।',
    recorderStatus: 'रिकॉर्डर स्थिति',
    startRecording: 'रिकॉर्डिंग शुरू करें',
    stopRecording: 'रिकॉर्डिंग बंद करें',
    voiceLog: 'वॉयस लॉग',
    textLog: 'टेक्स्ट लॉग',
    healthAssessment: 'स्वास्थ्य मूल्यांकन',
    mood: 'मूड',
    appetite: 'भूख',
    movement: 'गति',
    agitated: 'उत्तेजित',
    calm: 'शांत',
    low: 'कम',
    high: 'उच्च',
    slow: 'धीमा',
    active: 'सक्रिय',
    injuriesReport: 'चोट / रिपोर्ट करें',
    enterInjuries: 'कोई चोट या विशिष्ट अवलोकन दर्ज करें...',
    submitVoiceLog: 'वॉयस लॉग सबमिट करें',
    excellent: 'उत्कृष्ट',
    good: 'अच्छा',
    fair: 'ठीक',
    poor: 'खराब',
    alerts: 'अलर्ट',
    settings: 'सेटिंग्स',
    notifications: 'सूचनाएं',
    logout: 'लॉगआउट',
    cancel: 'रद्द करें',
    sendAlert: 'अलर्ट भेजें',
    sosAlert: 'SOS अलर्ट',
    manageUsers: 'उपयोगकर्ता प्रबंधित करें',
    addAnimal: 'जानवर जोड़ें',
    mediaUploads: 'मीडिया अपलोड',
    uploadImage: 'छवि अपलोड करें',
    uploadVideo: 'वीडियो अपलोड करें',
    transcribingAudio: 'ऑडियो ट्रांसक्राइब हो रहा है, कृपया प्रतीक्षा करें...',
    transcriptionSuccess: 'ऑडियो सफलतापूर्वक ट्रांसक्राइब हो गया!',
    transcriptionError: 'ऑडियो ट्रांसक्राइब करने में विफल।',
    shareWith: 'साझा करें',
    selectUsersToShare: 'इस लॉग को साझा करने के लिए व्यक्तिगत उपयोगकर्ताओं का चयन करें',
    notifyVetDepartment: 'इस लॉग की पशु चिकित्सा विभाग को सूचित करें',
    healthReports: 'स्वास्थ्य रिपोर्ट',
    voiceLogs: 'वॉयस लॉग',

    // Voice Recording Questions - Animal Health
    question1: 'आज जानवर ने खाना और पानी कैसे लिया, और उसका पाचन कैसा रहा?',
    question2: 'क्या आज जानवर में कोई चोट, बीमारी, कमजोरी या असामान्य शारीरिक स्थिति दिखाई दी?',
    question3: 'आज जानवर का व्यवहार और गतिविधि सामान्य थी या कुछ अलग दिखाई दी?',
    question4: 'क्या आज किसी प्रकार की मेटिंग, हीट की स्थिति, गर्भावस्था या बच्चे का जन्म देखा गया?',
    question5: 'क्या आज बाड़े में किसी जानवर की मृत्यु या गंभीर स्थिति देखी गई?',
    question6: 'आज बाड़े और आसपास की साफ़-सफाई और रखरखाव की स्थिति कैसी रही?',
    question7: 'क्या आज स्वच्छता, मच्छर, मक्खी या सुरक्षा से जुड़ी कोई समस्या देखी गई?',
    question8: 'क्या आज कर्मचारियों की उपस्थिति, वर्दी और स्वास्थ्य की स्थिति सामान्य रही?',
    question9: 'क्या आज कोई अन्य विशेष या महत्वपूर्ण बात है जिसे दर्ज किया जाना चाहिए?',

    // Voice Recording Questions - Enclosure Health
    question10: 'क्या बाड़े की सफाई जांची गई?',
    question11: 'क्या पानी का गर्त साफ किया गया?',
    question12: 'क्या बाड़ की स्थिति संतोषजनक है?',
    question13: 'खाई की स्थिति क्या है - सूखी या गीली?',
    question14: 'क्या मक्खी और मच्छर नियंत्रण उपाय किए गए?',
    question15: 'क्या कर्मचारियों की वर्दी और स्वास्थ्य संतोषजनक है?',
    question16: 'क्या साप्ताहिक सफाई सोडियम हाइपोक्लोराइट या चूने के पानी से की गई?',
  },
};
